### ISSUE TITLE
Use configuration file for key mappings

### ISSUE THREAD

**Issue by dceluis** [maricn/interception-vimproved#6]
Hi @maricn 

First, thank you for this great library. I've used it for more than a year now, and it's just become an indispensable part of my workflow.

I am not using the default key map, though. To do that, I had modify the source files directly and rebuild it locally.

I'm seeing a couple of forks popping up with some custom mappings as well. They might run into the same problem I just noticed: the library has been updated since I forked and built my own version, so I'm running an outdated version.

Would you be interested in adding the option to define custom mappings through a configuration file? I don't code C++ at all but I'm savvy enough to modify mappings from source. Maybe with some effort and guidance I can help with making the key maps be loaded from a config file.

Let me know if that's a change that you would be willing to merge into your library.

Thanks!

**Comment by maricn** [comment]
Hi @dceluis !

I like the idea, however I will not have time to work on it until mid-December at earliest. A PR submission to implement it is more than welcome. Thanks!

**Comment by 662929** [comment]
@dceluis preliminary implemented in #7.
Currently working on customizing new layers.
You can define the mapping for the space layer in yaml. You need to pass the absolute path to your `config.yaml` as  a commandline parameter to `interception-vimproved`.
Let us know if it works for you!

**Comment by dceluis** [comment]
Thank you for working on this @exprpapi . Looks awesome! I will try the yaml mappings sometime this week.
