### ISSUE TITLE
Please tag your Releases

### ISSUE THREAD

**Issue by vinay-keshava** [maricn/interception-vimproved#9]
Please tag your Releases,so it would be helpful to track version 

--
Debian Packaging Team

**Comment by maricn** [comment]
Hi @vinay-keshava, thank you for reaching out. I haven't technically "released" any version yet on GitHub, but it's a good point to start doing that regardless of package managers.. So, here you go - https://github.com/maricn/interception-vimproved/releases/tag/v0.1.0 

_Feel free to reopen the issue if you need something else._

**Comment by vinay-keshava** [comment]
@maricn thanks
